import { tv, type VariantProps } from "tailwind-variants";
import type { ComponentContract, MustBeNever, ThemeOverride, TVSlot } from "@75neo/core";
import { eachColor } from "../colors";

/**
 * Recipe for the Button: one interactive box holding an optional leading icon, a
 * label, and an optional trailing icon.
 *
 * @remarks
 * `variant` and `color` are independent, so the two together describe a table of forty
 * two cells. Six of those columns are generated by `eachColor`, because every hued
 * color spends itself the same way and only the name changes. The seventh, `neutral`,
 * is written out: it has no hue, so it borrows the surface tokens instead.
 *
 * Size is padding rather than a fixed height, so a button grows with whatever type
 * scale it inherits instead of clipping.
 *
 * `loading`, `leading` and `trailing` are variants rather than adapter logic, which is
 * what puts the spinner on whichever icon slot is actually rendered — including a
 * caller's own `loadingIcon`.
 */
export const button = tv({
  slots: {
    base: "inline-flex cursor-pointer items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-3 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75",
    label: "truncate",
    leadingIcon: "shrink-0 [&>svg]:size-full",
    trailingIcon: "shrink-0 [&>svg]:size-full",
  },
  variants: {
    variant: {
      solid: "",
      outline: "",
      soft: "",
      subtle: "",
      ghost: "",
      link: "",
    },
    color: {
      primary: "",
      secondary: "",
      success: "",
      info: "",
      warning: "",
      error: "",
      neutral: "",
    },
    size: {
      xs: {
        base: "gap-1 px-2 py-1 text-xs",
        leadingIcon: "size-4",
        trailingIcon: "size-4",
      },
      sm: {
        base: "gap-1.5 px-2.5 py-1.5 text-xs",
        leadingIcon: "size-4",
        trailingIcon: "size-4",
      },
      md: {
        base: "gap-1.5 px-2.5 py-1.5 text-sm",
        leadingIcon: "size-5",
        trailingIcon: "size-5",
      },
      lg: {
        base: "gap-2 px-3 py-2 text-sm",
        leadingIcon: "size-5",
        trailingIcon: "size-5",
      },
      xl: {
        base: "gap-2 px-3 py-2 text-base",
        leadingIcon: "size-6",
        trailingIcon: "size-6",
      },
    },
    /** Fill the container, with the trailing icon pushed to the far edge. */
    block: {
      true: {
        base: "w-full justify-center",
        trailingIcon: "ms-auto",
      },
    },
    /** Equal padding on all four sides, for a button holding only an icon. */
    square: {
      true: "",
    },
    leading: {
      true: "",
    },
    trailing: {
      true: "",
    },
    loading: {
      true: "",
    },
  },
  compoundVariants: [
    ...eachColor((color) => ({
      color,
      variant: "solid" as const,
      class: `bg-${color} text-inverted outline-${color}/25 hover:bg-${color}/75 active:bg-${color}/75 disabled:bg-${color} aria-disabled:bg-${color}`,
    })),
    ...eachColor((color) => ({
      color,
      variant: "outline" as const,
      class: `text-${color} ring ring-${color}/50 outline-${color}/25 ring-inset hover:bg-${color}/10 focus-visible:ring-${color} active:bg-${color}/10`,
    })),
    ...eachColor((color) => ({
      color,
      variant: "soft" as const,
      class: `bg-${color}/10 text-${color} outline-${color}/25 hover:bg-${color}/15 active:bg-${color}/15 disabled:bg-${color}/10 aria-disabled:bg-${color}/10`,
    })),
    ...eachColor((color) => ({
      color,
      variant: "subtle" as const,
      class: `bg-${color}/10 text-${color} ring ring-${color}/25 outline-${color}/25 ring-inset hover:bg-${color}/15 focus-visible:ring-${color} active:bg-${color}/15 disabled:bg-${color}/10 aria-disabled:bg-${color}/10`,
    })),
    ...eachColor((color) => ({
      color,
      variant: "ghost" as const,
      class: `text-${color} outline-${color}/25 hover:bg-${color}/10 active:bg-${color}/10`,
    })),
    ...eachColor((color) => ({
      color,
      variant: "link" as const,
      class: `text-${color} underline-offset-4 outline-${color}/25 hover:text-${color}/75 hover:underline active:text-${color}/75`,
    })),
    {
      color: "neutral",
      variant: "solid",
      class:
        "bg-inverted text-inverted outline-inverted/25 hover:bg-inverted/90 active:bg-inverted/90 disabled:bg-inverted aria-disabled:bg-inverted",
    },
    {
      color: "neutral",
      variant: "outline",
      class:
        "bg-default text-default ring ring-accented outline-inverted/25 ring-inset hover:bg-elevated focus-visible:ring-inverted active:bg-elevated",
    },
    {
      color: "neutral",
      variant: "soft",
      class:
        "bg-elevated text-default outline-inverted/25 hover:bg-accented/75 active:bg-accented/75",
    },
    {
      color: "neutral",
      variant: "subtle",
      class:
        "bg-elevated text-default ring ring-accented outline-inverted/25 ring-inset hover:bg-accented/75 focus-visible:ring-inverted active:bg-accented/75",
    },
    {
      color: "neutral",
      variant: "ghost",
      class: "text-default outline-inverted/25 hover:bg-elevated active:bg-elevated",
    },
    {
      color: "neutral",
      variant: "link",
      class:
        "text-muted underline-offset-4 outline-inverted/25 hover:text-default hover:underline active:text-default",
    },
    { size: "xs", square: true, class: "p-1" },
    { size: "sm", square: true, class: "p-1.5" },
    { size: "md", square: true, class: "p-1.5" },
    { size: "lg", square: true, class: "p-2" },
    { size: "xl", square: true, class: "p-2" },
    { loading: true, leading: true, class: { leadingIcon: "animate-spin" } },
    { loading: true, leading: false, trailing: true, class: { trailingIcon: "animate-spin" } },
  ],
  defaultVariants: {
    variant: "solid",
    color: "primary",
    size: "md",
  },
});

export type ButtonVariants = VariantProps<typeof button>;
export type ButtonSlots = keyof ReturnType<typeof button>;

export type ButtonUI = TVSlot<ButtonSlots>;

export type ButtonTheme = ThemeOverride<ButtonSlots, ButtonVariants>;

/**
 * Everything a Button accepts in both frameworks. Each adapter adds its own framework
 * props on top.
 *
 * @typeParam F - However the framework spells an icon: `ReactNode` in React,
 * `Component` in Vue.
 *
 * @remarks
 * The variant props are written out by hand because `defineProps` in Vue cannot read
 * them off the recipe. The guard below keeps them in step.
 */
export interface ButtonProps<F> {
  /** Per-slot class overrides. */
  ui?: ButtonUI;
  variant?: ButtonVariants["variant"];
  size?: ButtonVariants["size"];
  color?: ButtonVariants["color"];
  /** Fill the container's width. */
  block?: boolean;
  /**
   * Equal padding on all sides. Defaults to whether the button has a label, so an
   * icon-only button is square without being told.
   */
  square?: boolean;
  disabled?: boolean;
  /** Spins whichever icon slot is showing, and disables the button. */
  loading?: boolean;
  /** Replaces the default spinner. */
  loadingIcon?: F;
  /** Reserve the leading slot even when it holds nothing, to keep labels aligned. */
  leading?: boolean;
  /** Reserve the trailing slot even when it holds nothing. */
  trailing?: boolean;
  leadingIcon?: F;
  trailingIcon?: F;
}

/** Compile-time guard: a recipe variant with no matching prop above is a type error. */
export type ButtonVariantsAreExposed = MustBeNever<
  Exclude<keyof ButtonVariants, keyof ButtonProps<unknown>>
>;

declare global {
  interface Neo75ComponentThemes {
    button: ComponentContract<ButtonSlots, ButtonVariants>;
  }
}

/**
 * Decide which of Button's icon slots render, and where the spinner goes.
 *
 * @param props - `hasLeading` and `hasTrailing` are the adapter's answer to "is there
 * content for this slot": a non-null icon prop in React, an icon prop or a filled slot
 * in Vue.
 * @returns The `leading` and `trailing` variant values, which are also whether to
 * render each slot.
 *
 * @remarks
 * An empty slot still costs width, since the recipe sizes it and `base` puts a gap
 * between children. So a slot renders only when something fills it or the caller
 * reserved it on purpose.
 *
 * Loading is the one asymmetry. A button already showing a trailing icon and nothing
 * leading spins that trailing icon in place, rather than growing a second icon box on
 * the other side; anything else spins the leading one.
 */
export function resolveButtonIcons(props: {
  loading?: boolean;
  leading?: boolean;
  trailing?: boolean;
  hasLeading?: boolean;
  hasTrailing?: boolean;
}): { leading: boolean; trailing: boolean } {
  const trailing = Boolean(props.trailing || props.hasTrailing);
  const leading = Boolean(props.leading || props.hasLeading || (props.loading && !trailing));

  return { leading, trailing };
}
