export { default as TagsInput } from "./tags-input.vue";
export { default as TagsInputLabel } from "./label.vue";
export { default as TagsInputControl } from "./control.vue";
export { default as TagsInputItem } from "./item.vue";
export { default as TagsInputItemPreview } from "./item-preview.vue";
export { default as TagsInputItemText } from "./item-text.vue";
export { default as TagsInputItemDeleteTrigger } from "./item-delete-trigger.vue";
export { default as TagsInputItemInput } from "./item-input.vue";
export { default as TagsInputInput } from "./input.vue";
export { default as TagsInputClearTrigger } from "./clear-trigger.vue";
export { tagsInputVariantsKey, useTagsInputVariants } from "./variants";
