export { Dialog, type DialogProps } from "./dialog";
export { DialogTrigger, type DialogTriggerProps } from "./trigger";
export { DialogBackdrop, type DialogBackdropProps } from "./backdrop";
export { DialogContent, type DialogContentProps } from "./content";
export { DialogHeader, type DialogHeaderProps } from "./header";
export { DialogTitle, type DialogTitleProps } from "./title";
export { DialogDescription, type DialogDescriptionProps } from "./description";
export { DialogBody, type DialogBodyProps } from "./body";
export { DialogFooter, type DialogFooterProps } from "./footer";
export { DialogCloseTrigger, type DialogCloseTriggerProps } from "./close-trigger";
export { useDialogVariants } from "./variants";
